#!/bin/sh

sudo tlmgr install \
     collection-bibtexextra \
     collection-binextra \
     collection-fontsextra \
     collection-fontsrecommended \
     collection-fontutils \
     collection-formatsextra \
     collection-langcyrillic \
     collection-langenglish \
     collection-langeuropean \
     collection-langfrench \
     collection-langgerman \
     collection-langgreek \
     collection-langitalian \
     collection-latexextra \
     collection-luatex \
     collection-mathscience \
     collection-pictures \
     collection-plaingeneric \
     collection-pstricks \
     collection-publishers 
