#!/usr/bin/env bash

# red=$(xrdb -query  | grep color1  | sed 1q | awk '{print $2}')
# grn=$(xrdb -query  | grep color2  | sed 1q | awk '{print $2}')
# ylw=$(xrdb -query  | grep color3  | sed 1q | awk '{print $2}')

left=$(remind -naa ~/desk/remind/top.rem \
       | grep "$(date +'%Y/%m/%d')" \
       | awk '{$1=""; print}' \
       | sort \
       | sed 's/ today$//' \
       | sed "s/\(..*\)/%{F$ylw}\1/" \
       | paste -sd "," -)

right=$(remind -naa ~/desk/remind/top.rem \
	| grep "$(date -d 'tomorrow' +'%Y/%m/%d')" \
	| awk '{$1=""; print}' \
	| sort \
	| sed 's/ tomorrow$//' \
	| sed "s/\(..*\)/%{F$red}\1/" \
	| paste -sd "," -)

if test -n "$left" && test -n "$right"; then

    echo "today: $left  %{F$grn}  |  tomorrow: $right"

elif test -n "$left"; then

    echo "today: $left"

elif test -n "$right"; then

    echo "tomorrow: $right"

else

    echo ""

fi
