#!/usr/bin/env zsh

###     @@                           @@                  @@     @@              @@@@    @@
###    .@@                          .@@                 .@@    .@@             .@@.    .@@
###    .@@         @@@@@    @@@@@@  .@@        @@@@@@  @@@@@@  .@@   @@   @@  @@@@@@  @@@@@@
###    .@@@@@@    @@...@@  ..@@..@  .@@@@@@   @@....  ...@@.   .@@  .@@  .@@ ...@@.  ...@@.
###    .@@...@@  .@@@@@@@   .@@ .   .@@...@@ ..@@@@@    .@@    .@@  .@@  .@@   .@@     .@@
###    .@@  .@@  .@@....    .@@     .@@  .@@  .....@@   .@@    .@@  .@@  .@@   .@@     .@@
###    .@@  .@@  ..@@@@@@  .@@@     .@@@@@@   @@@@@@    ..@@   @@@  ..@@@@@@   .@@     ..@@
###    ..   ..    ......   ...      .....    ......      ..   ...    ......    ..       ..

herbstclient lock

# Try not to run twice?
#if [[ `pwd` != /home/blair/desk ]];
if pgrep gdm || pgrep lightdm; then
    blairstartup
fi

# notifications battery &
# notifications email   &
unclutter -noevents -root & 
# sxhkd 2> /dev/null &
sxhkd -c ~/.config/sxhkd/herbstluft_sxhkdrc 2> /dev/null &


hc () {
    herbstclient "$@"
}

{
    # xsetroot -cursor_name left_ptr &

    # theme
    hc attr theme.tiling.reset 1
    hc attr theme.floating.reset 1

    hc attr theme.tiling.border_width 2
    hc attr theme.floating.border_width 2
    # hc attr theme.tiling.normal.inner_width 2
    # hc attr theme.tiling.normal.outer_width 1
    #
    # hc attr theme.tiling.active.inner_width 0
    # hc attr theme.tiling.active.outer_width 3
    #
    # hc attr theme.floating.border_width 4
    # hc attr theme.floating.normal.outer_width 2
    # hc attr theme.floating.normal.inner_width 2
    # hc attr theme.floating.active.inner_width 0
    # hc attr theme.floating.active.outer_width 4

    # hc attr theme.border_width 5
    # hc attr theme.inner_width 4
    # hc attr theme.outer_width 1

    # hc attr theme.floating.border_width 5

    # set for compton transparency rules, see .compton.conf
    # see draw for monitor margins
    hc set focus_crosses_monitor_boundaries 1
    hc set always_show_frame                0
    hc set frame_bg_transparent             1
    hc set frame_border_width               0
    hc set frame_gap                        0
    hc set frame_padding                    0
    hc set frame_transparent_width          0
    hc set gapless_grid                     1
    hc set mouse_recenter_gap               0
    hc set smart_frame_surroundings         1
    hc set smart_window_surroundings        0
    hc set swap_monitors_to_get_tag         1

    hc set mouse_recenter_gap               0
    hc set default_frame_layout             3 # grid

    herbstclient set window_gap 0

    # herbstclient pad 0 -1 -1 -1 -1

} &

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )


# herbstclient new_attr string my_workgroup
# herbstclient attr my_workgroup default

hc rename default 0 || true
hc add 1
hc add 2
hc add 3
hc add 4
hc add 5
hc add 6
hc add 7
hc add 8
hc add 9

# hc add 10
# hc add 11
# hc add 12
# hc add 13
# hc add 14
# hc add 15
# hc add 16
# hc add 17
# hc add 18
# hc add 19

# hc add 20
# hc add 21
# hc add 22
# hc add 23
# hc add 24
# hc add 25
# hc add 26
# hc add 27
# hc add 28
# hc add 29




# rules
hc unrule -F
hc rule focus=on # normally focus new clients
# hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
#hc rule instance~"mpv" fullscreen=on
#hc rule title=pipes_SWAG_SWAG_SWAG fullscreen=on
#hc rule title=task_SWAG_SWAG_SWAG pseudotile=on
#hc rule class~"scratch.*"      pseudotile=on
hc rule class=9menu manage=off
# hc rule class~"scratch.*"      pseudotile=on manage=off hook=center

hc rule title=emacs-compose pseudotile=on


hc mouseunbind --all
hc mousebind Mod4-Button1 move
hc mousebind Mod4-Button2 zoom
hc mousebind Mod4-Button3 resize
hc mousebind Mod4-Shift-Button1 resize

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

herbstclient unlock

# hc pad 0 24 0 18 0
# hc pad 0 24 0 18 0
# polybar topbar &
# polybar botbar &


blk=$(xrdb -query  | grep color0  | sed 1q | awk '{print $2}')
bblk=$(xrdb -query | grep color8  | sed 1q | awk '{print $2}')
red=$(xrdb -query  | grep color1  | sed 1q | awk '{print $2}')
bred=$(xrdb -query | grep color9  | sed 1q | awk '{print $2}')
blu=$(xrdb -query  | grep color4  | sed 1q | awk '{print $2}')


hc attr theme.floating.normal.color   "$bblk"
hc attr theme.floating.active.color   "$red"
hc attr theme.floating.urgent.color   "#905656"

hc attr theme.tiling.normal.color   "$blu"
hc attr theme.tiling.active.color   "$red"
hc attr theme.tiling.urgent.color   "#905656"

hc attr theme.normal.outer_color   "#282828"
hc attr theme.active.outer_color   "#282828"
hc attr theme.urgent.outer_color   "#282828"

hc set  frame_border_normal_color  "$blk"
hc set  frame_border_active_color  "$bred"
