#!/usr/bin/env bash

attachments=0
while read line; do
    if [[ $(echo $line | grep '\[-- Attachment.*--\]') != "" ]]; then
	attachments=1
    fi
    echo $line \
	| grep -v '\[.*.gif\]' \
	| grep -v '\[-- Type.*--\]' \
	| grep -v '\[-- Autoview.*--\]' \
	| grep -v '\[-- Image.*--\]' \
	| grep -v '\[-- image.*--\]' 

done | t-prot -cemt -M=mutt | cat -s


# BEGIN {
#   cmd="echo '[automatically converted from html to text]'; w3m -T text/html -dump"
# }
# {l=tolower($0)}
# l ~ /<html|<!doctype html/,l ~ /<\/html>/ {
#   print | cmd
#   next
# }
# {close(cmd); print}
