#!/bin/sh

col_0=$(xrdb -query | grep "\*color0"  | sed '1q' | awk '{print $2}')
col_a=$(xrdb -query | grep "\*color6"  | sed '1q' | awk '{print $2}')
col_b=$(xrdb -query | grep "\*color4"  | sed '1q' | awk '{print $2}')
col_c=$(xrdb -query | grep "\*color2"  | sed '1q' | awk '{print $2}')
bg=$(xrdb -query | grep "background"   | sed '1q' | awk '{print $2}')

panel=black

title_col_a="$(convert -size 4x6  gradient:"$bg"-"$col_b" -crop 4x4+0+2 -resize 1x1 -depth 8 text:- | sed -n 2p | awk '{print $3}')"
title_col_b="$(convert -size 4x6  gradient:"$bg"-"$bg" -crop 4x4+0+0 -resize 1x1 -depth 8 text:- | sed -n 2p | awk '{print $3}')"

case "$1" in

    wallpaper)

	if test -n "$2"; then
	    wall="$2"
	else
	    pgrep compton || (compton &) > /dev/null 2>&1
	    theme=$(sed '1q' ~/.Xresources | sed 's~.*.colors/\([^>]*\)>~\1~')
	    wall="$HOME/desk/.wallpapers/${theme}.jpg"
	fi

	# feh --bg-fill "$wall" > /dev/null 2>&1

	title_col_a=$(convert "$wall" -resize 1x1 text: | sed 1d | awk '{print $3}')
	# title_col_b=$(convert "$wall" -crop 400x400+100+100 -resize 1x1 text: | sed -n 2p | awk '{print $3}')
	title_col_b=$col_0
	;;

    gradient)
	pgrep compton || (compton &)  > /dev/null 2>&1

	convert -size 4x4  gradient:"$col_a"-"$col_0" -distort SRT 60 -resize 1920x1080\!  /tmp/.gradient.png
	feh --bg-fill /tmp/.gradient.png
	;;

    blank)
	hsetroot -solid "$bg"  > /dev/null 2>&1
	panel="$col_a"
	;;

    bitmap)
	# Need to clean up the panel
	hsetroot -solid "$bg"  > /dev/null 2>&1
	pgrep compton && pkill compton  > /dev/null 2>&1
	panel="$col_a"
	random-bitmap > /dev/null 2>&1
	;;

    "")
	;;

    *)
	;;

esac

cat <<EOF
Colorset 4  RootTransparent buffer, fg   "$panel",    bg "$panel", hi black, tint black 0
Colorset 6  Root tint "$title_col_a"   100
Colorset 7  Root bg white, tint "$title_col_b"   100
Colorset 10 Root fg "$title_col_b" 
EOF
