#!/bin/sh

echo 
echo "DestroyMenu recreate EmacsMenu"
# echo AddToMenu EmacsMenu "Buffers" Title 
emacs-buffer-list gui | while read line; do
    # test -n "$line" && echo "AddToMenu EmacsMenu \"$line\"      Exec st -e client -t -e '(switch-to-buffer \"$line\")'"
    test -n "$line" && echo "AddToMenu EmacsMenu \"$line\"      Exec emacs-gui -e '(switch-to-buffer \"$line\")'"
done
echo "AddToMenu EmacsMenu \"~scratch~\"      Exec emacs-gui -e '(switch-to-buffer \"\*scratch\*\")'"
# echo
# echo "Popup EmacsMenu"
