#!/bin/sh


echo 
echo "DestroyMenu recreate InfoMenu"
# echo "AddToMenu InfoMenu \"Remind+Mail\" Title"

{
    remind -naa ~/desk/remind/top.rem \
	| grep "$(date +'%Y/%m/%d')" \
	| awk '{$1=""; print}' \
	| sort \
	| sed 's/ today$//' \
	| grep -v '^$'

    echo 
    remind -naa ~/desk/remind/top.rem \
	| grep "$(date -d 'tomorrow' +'%Y/%m/%d')" \
	| awk '{$1=""; print}' \
	| sort \
	| sed 's/ tomorrow$//' \
	| grep -v '^$'
    echo
    notmuch show --format=json tag:unread and tag:inbox 2> /dev/null | jq '.[][0][0].headers | [.From,.Subject] | @csv' | sed 's/[\\"]//g' | sed 's/ <.*>//g' | cut -c -50

} | paste -sd "\n" - | while read line; do
    if test -n "$line"; then
	nonempty=1
    fi
    if test -n "$nonempty"; then
	echo "AddToMenu InfoMenu \"$line\" Nop"
    fi
done

if test -z "$nonempty"; then
    echo "AddToMenu InfoMenu \"Nothing New $nonempty\" Nop"
fi

