#!/bin/bash

wid=$1
if [ "$wid" == "" ]
then
	exit 1
fi

dir=$2
if [ "$dir" == "" ]
then
	exit 2
fi

col=$(xrdb -query | grep "\*color6" | sed '1q' | awk '{print $2}')

xwd -silent -id "$wid" | convert -scale 200 -border 1x1 -bordercolor "$col" xwd:- png:"$dir"/"$wid".png

# xwd -silent -id "$wid" | convert -scale 200 xwd:- png:"$dir"/"$wid".png

cat <<END
Raise
WindowStyle IconOverride, Icon "$dir"/"$wid".png
Iconify
END

